---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/crate-ci/typos
    rev: v1.48.0
    hooks:
      - id: typos

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format

  - repo: https://github.com/cmake-lint/cmake-lint
    rev: 1.4.3
    hooks:
      - id: cmakelint

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1-1
    hooks:
      - id: shellcheck
        args: [--severity=warning]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        stages: [manual]
      - id: cppcheck
        stages: [manual]

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 44.91.0
    hooks:
      - id: renovate-config-validator
