---
name: Bug Report
description: Report a defect or regression.
title: "[BUG]: "
labels:

- "type: bug"

body:

- type: textarea
  id: description
  attributes:
    label: Bug Description
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: Expected Behaviour

- type: textarea
  id: actual
  attributes:
    label: Actual Behaviour

- type: textarea
  id: reproduction
  attributes:
    label: Steps To Reproduce